name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for finding issue, Lets resolve together'' first issue'
        pr-message: 'Thanks for Pull Request, I will check and merge soon'' first pr'
